import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        // Stitch / Material Design 3 design tokens
        'on-surface-variant': '#454558',
        'surface-bright': '#f8f9fa',
        primary: '#0001bb',
        'primary-fixed': '#e0e0ff',
        'primary-fixed-dim': '#bec2ff',
        'primary-container': '#0000ff',
        'on-primary': '#ffffff',
        'on-primary-container': '#b3b7ff',
        'on-primary-fixed': '#00006e',
        'on-primary-fixed-variant': '#0000ef',
        'on-surface': '#191c1d',
        'surface-container-highest': '#e1e3e4',
        'surface-container-high': '#e7e8e9',
        'surface-container': '#edeeef',
        'surface-container-low': '#f3f4f5',
        'surface-container-lowest': '#ffffff',
        'surface-variant': '#e1e3e4',
        surface: '#f8f9fa',
        background: '#f8f9fa',
        'on-background': '#191c1d',
        outline: '#757589',
        'outline-variant': '#c5c4db',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'on-error': '#ffffff',
        'surface-dim': '#d9dadb',
        'surface-tint': '#343dff',
        'inverse-primary': '#bec2ff',
        'inverse-surface': '#2e3132',
        'inverse-on-surface': '#f0f1f2',
        secondary: '#006e2a',
        'secondary-container': '#5cfd80',
        'secondary-fixed': '#69ff87',
        'secondary-fixed-dim': '#3ce36a',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#00732c',
        'on-secondary-fixed': '#002108',
        'on-secondary-fixed-variant': '#00531e',
        tertiary: '#4b3000',
        'tertiary-container': '#694400',
        'tertiary-fixed': '#ffddb3',
        'tertiary-fixed-dim': '#ffb950',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#ffab06',
        'on-tertiary-fixed': '#291800',
        'on-tertiary-fixed-variant': '#624000',
        success: '#00C853',
      },
      spacing: {
        'container-max': '1200px',
        'margin-mobile': '20px',
        'margin-desktop': '40px',
        gutter: '24px',
        unit: '8px',
      },
      borderRadius: {
        DEFAULT: '1rem',
        lg: '2rem',
        xl: '3rem',
        full: '9999px',
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-lg-mobile': ['32px', { lineHeight: '1.25', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '1.4', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', letterSpacing: '0', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.5', letterSpacing: '0', fontWeight: '400' }],
        'label-bold': ['14px', { lineHeight: '1', letterSpacing: '0.02em', fontWeight: '600' }],
        'label-md': ['14px', { lineHeight: '1', letterSpacing: '0', fontWeight: '500' }],
        caption: ['12px', { lineHeight: '1.4', letterSpacing: '0', fontWeight: '400' }],
      },
      fontFamily: {
        'headline-md': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'label-bold': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        caption: ['Inter', 'sans-serif'],
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic': 'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
      },
    },
  },
  plugins: [],
};
export default config;
